### ISSUE TITLE
Comprehensive TSV3 test suite

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#242]
Implement a comprehensive test suite for WebAnno TSV 3 to check most of the potentially problematic cases - if not all!.

Those tests that have a checkmark were already implemented. These may fail if the issues listed after them have not been closed yet.

**Span layers**
- [X] cross-sentence with feature value (`testCrossSentenceSpanWithFeatureValue`)
- [X] cross-sentence without feature value (`testCrossSentenceSpanWithoutFeatureValue`) (#240)
- [X] multi-token with feature value (`testMultiTokenSpanWithFeatureValue`)
- [X] multi-token without feature value (`testMultiTokenSpanWithoutFeatureValue`) (#240)
- [X] multi-token stacked with feature value (`testMultiTokenStackedSpanWithFeatureValue`) (#241)
- [X] multi-token stacked without feature value (`testMultiTokenStackedSpanWithoutFeatureValue`) (#240, #241)
- [X] multi-token fake BIO feature values (`testTokenBoundedBioLookAlike`) (#238)
- [X] single-token fake stacked feature values (`testTokenBoundedStackedLookAlike`)
- [X] single-token with asterisk feature value (`testTokenBoundedSpanWithAsteriskFeatureValue`) (#240)
- [X] single-token with underscore feature value (`testTokenBoundedSpanWithUnderscoreFeatureValue`)
- [X] single-token with `<typename>:<feature>` feature value (`testTokenBoundedSpanWithNastyFeatureValue`)
- [x] single-token without feature value (#240)
- [X] single-token with all kinds of symbols, tabs, newlines as feature value (`testTokenBoundedSpanWithSpecialSymbolsValue`) (#176)
- [X] single-token stacked with feature value (#239, #241)
- [X] zero-length with feature value
- [X] zero-length without feature value (#240)
- [X] zero-length without any feature at all (#231)
- [x] zero-length stacked without feature value (#240,#241)

**Span layers with slot feature**
- [x] multiple slot feature with single target each (`testSimpleSlotFeature`) (#285)
- [X] single span with single slot features with multiple targets each (`testSimpleSameRoleSlotFeature`)
- [X] cross-sentence slot feature (`testSimpleCrossSenenceSlotFeature`)
- [X] multi-token slot fillers (`testMultiTokenSlotFeature`)
- [X] stacked multi-token slot fillers (`testMultiTokenStackedSlotFeature`)
- [X] zero-length span with slot feature (`testZeroLengthSlotFeature1`)
- [x] zero-length slot filler (`testZeroLengthSlotFeature2`) (#294)

**Relation layers**
- [x] single-token (Token) relation without feature (`testSingleNonTokenRelationWithoutFeature`)
- [x] single-token (Token) relation without feature value (`testSingleTokenRelationWithoutFeatureValue`)
- [x] single-token (non-Token) relation without feature value (`testSingleNonTokenRelationWithoutFeatureValue`)
- [x] single-token relation with feature value (`testSingleTokenRelationWithFeatureValue`)
- [x] multi-token (non-Token) relation without feature value (#260) (`testSingleNonMultiTokenRelationWithoutFeatureValue`)
- [x] single-token stacked relation without feature value (`testSingleStackedNonTokenRelationWithoutFeatureValue`)
- [x] single/multi-token stacked relation with overlapping spans without feature value (`testSingleStackedNonTokenOverlappingRelationWithoutFeatureValue`)
